# Generated by Django 3.2.9 on 2022-02-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220205_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
